## Python: NumPy

__[Pure Python, NumPy, Pandas, and TensorFlow]__

List는 저장용량과 시간을 많이 소모하는 단점이 있다. 이를 보완하기 위해 수치연산에 특화되어 있는 NumPy를 사용한다. NumPy keeps __the same type of data in arrays__. TensorFlow는 연산과정을 그래프화하여 시각화할 수 있다. TensorFlow는 값의 변화 과정을 시각화하여 관찰할 수 있다. Pandas는 빅데이터 환경과 같은 많은 데이터를 효율적으로 처리할 수 있는 장점이 있다.

__1. NumPy:type, dtype, shape, dimension, size__

- Data types are the same in an array.

- Rank: the (linearly independent) number of variables in a matrix.

In [2]:
# Create a rank one array with the array function
import numpy as np # numpy라이브러리 실행
a = np.array([7,8,9,10,11])
print(f'{a}\n{"object type:":>12} {type(a)}\n{"data type:":>12} {a.dtype}\n{"shape:":>12} \
{a.shape}\n{"dimension:":>12} {a.ndim}\n{"array size:":>12} {a.size}') #너무 길어서 줄을 바꾸고 싶을 때는 역슬래쉬(\)를 사용
a1 = np.array([a]); print(a1.shape) #대괄호의 개수에 따라 차원을 나눌 수 있다.

a2 = [7, 8, 9, 10, 11]; print(a2) #list와 numpy의 차이점

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (5,)
  dimension: 1
 array size: 5
(1, 5)
[7, 8, 9, 10, 11]


In [8]:
b = np.array([[1.0,2, 3, 4, 5], [8,9,10,11,12.2]])
print(f'{b}\n{"object type:":>12} {type(b)}\n{"data type:":>12} {b.dtype}\n{"shape:":>12} \
{b.shape}\n{"dimension:":>12} {b.ndim}\n{"array size:":>12} {b.size}')

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type: <class 'numpy.ndarray'>
  data type: float64
      shape: (2, 5)
  dimension: 2
 array size: 10


In [9]:
c = np.array([[[1,2,3,4,5],[8,9,10,11,12]],[[4,5,6,7,8],[10,11,12,13,14]]])
print(f'{c}\n{"object type:":>12} {type(c)}\n{"data type:":>12} {c.dtype}\n{"shape:":>12} \
{c.shape}\n{"dimension:":>12} {c.ndim}\n{"array size:":>12} {c.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (2, 2, 5)
  dimension: 3
 array size: 20


In [10]:
ac1 = np.array([[[1,2,3,4,5],[8,9,10,11,12]]])
print(f'{ac1}\n{"object type:":>12} {type(ac1)}\n{"data type:":>12} {ac1.dtype}\n{"shape:":>12} \
{ac1.shape}\n{"dimension:":>12} {ac1.ndim}\n{"array size:":>12} {ac1.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (1, 2, 5)
  dimension: 3
 array size: 10


In [11]:
ac2 = np.array([[[1,2,3,4,5]]])
print(f'{ac2}\n{"object type:":>12} {type(ac2)}\n{"data type:":>12} {ac2.dtype}\n{"shape:":>12} \
{ac2.shape}\n{"dimension:":>12} {ac2.ndim}\n{"array size:":>12} {ac2.size}')

[[[1 2 3 4 5]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (1, 1, 5)
  dimension: 3
 array size: 5


__2.NumPy:special arrays and indexing__

In [15]:
a_zeros = np.zeros((2, 3))
print(a_zeros)
a_ones = np.ones((2, 4), dtype=int)
print(a_ones)
a_full = np.full((2, 5),7)
print(a_full)
print(np.eye(3)) #identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
a_ran = np.random.random((2, 3, 4))
print(f'{a_ran}\n{a_ran.dtype}')

[[[0.87281673 0.81625466 0.81918848 0.87508231]
  [0.76629781 0.75595565 0.53770413 0.96921059]
  [0.65533479 0.33161887 0.28867249 0.7239887 ]]

 [[0.81165354 0.90644451 0.91824282 0.01042593]
  [0.72065999 0.24595108 0.99902755 0.21913833]
  [0.60533456 0.54644034 0.79202402 0.97620592]]]
float64


In [19]:
print(c)
print(c[1,0,4])
print(c[1][0][4])
print(c[0,0,4])

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
8
8
5


__3.NumPy:flattening and making arrays with arange function__

In [22]:
# flattening the c array in a row using for loop. = 다차원 배열을 일차원으로 바꾸는 것
print(c)
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}')

# flattening
print(np.array(c.flat))

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


In [24]:
g = np.arange(21) #numpy에서는 arange 사용 list에서는 range
print(f'{g}\n{type(g)}')
print(g.reshape(1, 3, 7)) #모양틀을 설정하는 방법

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [25]:
h = np.arange(5, 21, 2) # arange 와 range의 사용 방법은 같다.
print(h)
print(np.arange(1, 21).reshape(2, 10)) # chained method calls

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [28]:
# Creating an array of equal space within a range
a_ss = np.linspace(0,1,11) #동일한 간격으로 나누는 방법 the ending value is inclusive(마지막 숫자도 포함)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11


__4.NumPy: Array operations__

- Operations on all elements of arrays

In [6]:
# element_wise operations(내적)
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape, xb.shape) # 배열의 차원이 완전히 일치하는 경우 element-wise 연산이 가능하다.
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [9]:
# element-wise operations
print(np.add(xa,xb)) # 더하기
print(np.subtract(xa, xb)) # 빼기
print(np.multiply(xa,xb)) # 곱하기
print(np.sqrt(xa)) # 나누기(루트 씌우기)

[[ 4  6]
 [ 8 10]
 [12 14]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[ 3  8]
 [15 24]
 [35 48]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [12]:
# inner product of matrix (행렬의 inner product연산의 경우 두 행렬의 정합성이 맞아야 한다. ex. 3-2 * 2-3
xc = np.ones((2,1))
print(xc, xc.shape, xc.ndim)
print(xa.dot(xc))
print(np.dot(xb,xc))

[[1.]
 [1.]] (2, 1) 2
[[ 3.]
 [ 7.]
 [11.]]
[[ 7.]
 [11.]
 [15.]]


In [16]:
xd = np.array([[1,2],[1,2]]); print(xd)
print(np.dot(xa, xd));print(np.dot(xb,xd)) # 행렬의 곱셈 참고

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [18]:
print(xa.T) # Transform(변환)
print(xb+3)
print(xb)
xb += 3
print(xb)

[[1 3 5]
 [2 4 6]]
[[ 9 10]
 [11 12]
 [13 14]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 9 10]
 [11 12]
 [13 14]]


__5.NumPy: Broadcasting__

- Arithmetic operation between different shaped arrays

In [20]:
ya = np.arange(1, 10).reshape(3,3); print(ya)
yv1 = np.ones((3,1)); print(yv1)
yb = ya + yv1; print(yb)
yv2=np.full((1,3),2); print(yv2)
yc = ya + yv2; print(yc)
# Broadcasting rule이 적용되면 차원이 다른 matrix들간의 연산이 가능해진다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.]
 [1.]
 [1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [21]:
yd = np.arange(1, 10).reshape(3,3); print(ya)
yv3 = np.array([[1],[2],[3]]); print(yv3)
yyd = yd + yv3; print(yyd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


__6.NumPy: Summary Statistics__

In [27]:
# Uses all elements in calculations
print(yc.sum(), yc.mean(), yc.min(), yc.max(), yc.var(), yc.std())
print(yc.argmax(), yc.argmin())
print(yc.mean(axis=0), yc.mean(axis=1)) # 0 vertically, 1 horizontally

63 7.0 3 11 6.666666666666667 2.581988897471611
8 0
[6. 7. 8.] [ 4.  7. 10.]


__7.NumPy:Slicing, Flatten, and Stacking__

In [24]:
karray=np.arange(21).reshape(3, 7); print(karray)
print(karray[0], karray[0,:4])
print(karray[:2]) # ,가 없는 경우는 row만 인식한다는 것
print(karray[:2, :3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[0 1 2 3 4 5 6] [0 1 2 3]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0 1 2]
 [7 8 9]]


In [26]:
karray=np.arange(21).reshape(3,7); print(karray)
print(karray[[0,2]])
print(karray[:,[1,5]]) # column중에서 1 하고 5
print(karray[:,1:5]) # column중에서 1 부터 5

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]
[[ 1  5]
 [ 8 12]
 [15 19]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [33]:
# reshape does not change original array shape but resize does
karray=np.arange(21).reshape(3,7); print(karray)
fkarray=karray.flatten() # into a single dimension array
print(fkarray, fkarray.shape)
fkarray1 = np.array(karray.flat)
print(fkarray1)
rfkarray = karray.reshape(1, 21)
print(rfkarray, rfkarray.shape)
rfkarray.resize(3,7)
print(rfkarray, rfkarray.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]] (1, 21)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] (3, 7)


In [35]:
# stacking
karray1 = karray[:,:3]; karray2 = karray[:,3:6]
karrayh = np.hstack([karray1, karray2]); print(karrayh) # 가로로 쌓기
karrayv = np.vstack([karray1, karray2]); print(karrayv) # 세로로 쌓기

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]]
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [ 3  4  5]
 [10 11 12]
 [17 18 19]]
